# Generated by Django 3.0.3 on 2020-02-11 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Time_Capsule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('contents', models.TextField(default='')),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_capsules', to='timeline.Timeline')),
            ],
        ),
    ]
