# Generated by Django 3.0.3 on 2020-02-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='time_capsule',
            name='image',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='time_capsule',
            name='sound',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='time_capsule',
            name='useful_links',
            field=models.TextField(default=''),
        ),
    ]
