# Generated by Django 3.0.3 on 2020-02-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_auto_20200212_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time_capsule',
            name='sound',
        ),
        migrations.AddField(
            model_name='time_capsule',
            name='video',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='time_capsule',
            name='contents',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='time_capsule',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='time_capsule',
            name='useful_links',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
