# Generated by Django 3.0.3 on 2020-02-12 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0003_auto_20200212_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeline',
            name='author',
        ),
    ]
